sudo: false
language: node_js
node_js:
  - 'iojs-2'
  - 'iojs-1'
  - '0.12'
  - '0.11.12'
  - '0.10'
script: "npm run test-travis"
after_script: "npm install coveralls@2 && cat ./coverage/lcov.info | coveralls"
