environment:
  matrix:
    - nodejs_version: '0.10'
    - nodejs_version: '0.12'
    - nodejs_version: '4'
    - nodejs_version: '6'
    - nodejs_version: '7'

install:
  - ps: Install-Product node $env:nodejs_version
  - npm i npm && node_modules\.bin\npm i

test_script:
  - npm run ci

build: off
