name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  merge_group:

jobs:
  typecheck:
    runs-on: ubuntu-latest
    concurrency:
      group: typecheck-${{ github.workflow }}-#${{ github.event.pull_request.number || github.head_ref || github.ref }}
      cancel-in-progress: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6

      - name: Set up Node.js
        uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6
        with:
          node-version: '24'

      - name: Setup Vite+
        uses: voidzero-dev/setup-vite-plus-action@v1
        with:
          cache: true
          run-install: true

      - name: Run lint
        run: vite run lint

      - name: Check dedupe
        run: vite dedupe --check

      - name: Run typecheck
        run: vite run typecheck

      - name: Run format check
        run: vite run fmtcheck

      - name: Run build check
        run: vite run build

  test:
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest', 'macos-latest', 'windows-latest']
        node: ['20', '22', '24', '25']

    name: Test (${{ matrix.os }}, ${{ matrix.node }})
    runs-on: ${{ matrix.os }}

    concurrency:
      group: test-${{ github.workflow }}-#${{ github.event.pull_request.number || github.head_ref || github.ref }}-(${{ matrix.os }}, ${{ matrix.node }})
      cancel-in-progress: true

    permissions:
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6

      - name: Set up Node.js
        uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6
        with:
          node-version: ${{ matrix.node }}

      - name: Setup Vite+
        uses: voidzero-dev/setup-vite-plus-action@v1
        with:
          cache: true
          run-install: true

      - name: Run lint
        run: vite run lint

      - name: Run tests
        run: vite run ci

      - name: Code Coverage
        uses: codecov/codecov-action@671740ac38dd9b0130fbe1cec585b89eea48d3de # v5
        with:
          use_oidc: true
