name: Publish Any Commit
on: [push, pull_request]

jobs:
  build:
    concurrency:
      group: pkg-pr-new-${{ github.workflow }}-#${{ github.event.pull_request.number || github.head_ref || github.ref }}
      cancel-in-progress: true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - run: corepack enable
      - uses: actions/setup-node@v6
        with:
          node-version: 22

      - name: Setup Vite+
        uses: voidzero-dev/setup-vite-plus-action@v1
        with:
          cache: true
          run-install: true

      - name: Build
        run: vite run build

      - run: vite dlx pkg-pr-new publish
